.TH "BOSCO-CLEAN" "3" "April 2024" "" ""
.SH "NAME"
\fBbosco-clean\fR - Clean node_modules and re-run npm install.
.SH "SYNOPSIS"
.P
.RS 2
.nf
bosco clean -r <repoPattern>
.fi
.RE
.SH "DESCRIPTION"
.P
This command is used to clean out node_modules and re-run npm install.
.SH "COMMAND LINE OPTIONS"
.SS "-r, --repo"
.RS 0
.IP \(bu 4
Default: .*
.IP \(bu 4
Type: String
.RE 0

.P
This sets a regex string to use to filter the repostory list.
