.TH "BOSCO-PULL-GIT" "3" "April 2024" "" ""
.SH "NAME"
\fBbosco-pull-git\fR - Run 'git pull --rebase master' across all repositories in your Github team.
.SH "SYNOPSIS"
.P
.RS 2
.nf
bosco pull-git
bosco pull-git -r <repoPattern>
.fi
.RE
.SH "DESCRIPTION"
.P
This command is used to pull changes from all of the github repositories in your configured Github team.
.P
It is called as part of the wrapper script: \fBmorning\fR.
.SH "COMMAND LINE OPTIONS"
.SS "-r, --repo"
.RS 0
.IP \(bu 4
Default: .*
.IP \(bu 4
Type: String
.RE 0

.P
This sets a regex string that is used to filter the repository list.
.SH "SEE ALSO"
.RS 0
.IP \(bu 4
bosco help morning
.RE 0
