.TH "BOSCO-SETUP" "3" "April 2024" "" ""
.SH "NAME"
\fBbosco-setup\fR - Setup your local environment.
.SH "SYNOPSIS"
.P
.RS 2
.nf
bosco setup
.fi
.RE
.SH "DESCRIPTION"
.P
This command is intended to be used when first running Bosco within a new team configuration. It is simply a wrapper around two commands: bosco-clone(3) and bosco-install(3).
.SH "SEE ALSO"
.RS 0
.IP \(bu 4
bosco-clone(3)
.IP \(bu 4
bosco-install(3)
.RE 0
