.TH "BOSCO-TEAM" "3" "December 2020" "" ""
.SH "NAME"
\fBbosco-team\fR - Manage your github teams
.SH "SYNOPSIS"
.P
.RS 2
.nf
bosco team
bosco team ls
bosco team sync
bosco team ln <team> <folder>
.fi
.RE
.SH "DESCRIPTION"
.P
This command allows you to configure and manage your github teams.
.SS "bosco team ls"
.P
List teams - this will list each of the teams and the workspace folders they are currently linked to.
.SS "bosco team sync"
.P
Synchronise your github team list with bosco - run this whenever you add a new team to Github. This is also called by 'bosco setup', so you may just run that command whenever you change your teams as it also then runs a 'bosco team ln'.
.SS "bosco team ln  "
.P
Link a team to a workspace.
.P
.RS 2
.nf
bosco team ln tes/resources .
bosco team ln tes/profiles /User/cliftonc/work/profiles
.fi
.RE
.P
This command then ensures that any bosco commands run in this workspace recognise they are part of this team, and so use the cached repository list.
.SH "SEE ALSO"
.RS 0
.IP \(bu 4
bosco help setup
.RE 0
