.TH "BOSCO-MORNING" "3" "December 2020" "" ""
.SH "NAME"
\fBbosco-morning\fR - The command you run every day.
.SH "SYNOPSIS"
.P
.RS 2
.nf
bosco morning
.fi
.RE
.SH "DESCRIPTION"
.P
This command is a simple wrapper around: clone > pull > install. Most people run this command in the morning to ensure their local working environment is completely up to speed with any changes made by their team over night.
.P
It is a wrapper around four scripts: \fBclone\fR, \fBpull\fR, \fBinstall\fR and \fBactivity\fR.
.SH "SEE ALSO"
.RS 0
.IP \(bu 4
bosco help clone
.IP \(bu 4
bosco help pull
.IP \(bu 4
bosco help install
.IP \(bu 4
bosco help activity
.RE 0
