.TH "BOSCO-GREP" "3" "December 2020" "" ""
.SH "NAME"
\fBbosco-grep\fR - Grep through all of your repos.
.SH "SYNOPSIS"
.P
.RS 2
.nf
bosco grep <pattern>
.fi
.RE
.SH "DESCRIPTION"
.P
This command runs \fBgit grep\fR across all of your repos with the given pattern.
.SH "EXAMPLES"
.P
.RS 2
.nf
bosco grep MyClass
.fi
.RE
