.TH "BOSCO-UPSTREAM" "3" "December 2020" "" ""
.SH "NAME"
\fBbosco-upstream\fR - Write out any changes that have occurred in upstream branches
.SH "SYNOPSIS"
.P
.RS 2
.nf
bosco upstream
bosco -r <repoPattern> upstream
.fi
.RE
.SH "DESCRIPTION"
.P
This command is used to list out any upstream changes (before a pull, stash etc.) in your repositories.
.SH "COMMAND LINE OPTIONS"
.SS "-r, --repo"
.RS 0
.IP \(bu 4
Default: .*
.IP \(bu 4
Type: String
.RE 0

.P
This sets a regex string to use to filter the repostory list.
