.TH "BOSCO-ACTIVITY" "3" "December 2020" "" ""
.SH "NAME"
\fBbosco-activity\fR - Show a rundown of what has been happening across all the repositories.
.SH "SYNOPSIS"
.P
.RS 2
.nf
bosco activity
bosco activity -r <repoPattern>
bosco activity -r <repoPattern> --since <timestamp>
.fi
.RE
.SH "DESCRIPTION"
.P
This command will show a summary of all the commits across all the repositories - used as part of the \fBmorning\fR command.
.SH "EXAMPLES"
.P
.RS 2
.nf
bosco activity -r review --since 2014-09-22T23:36:26-07:00
.fi
.RE
.SH "COMMAND LINE OPTIONS"
.SS "-r, --repo"
.RS 0
.IP \(bu 4
Default: .*
.IP \(bu 4
Type: String
.RE 0

.P
This sets a regex string to use to filter the repostory list.
.SS "-s, --since"
.RS 0
.IP \(bu 4
Default: Previous 24 hours
.IP \(bu 4
Type: Timestamp (e.g. 2014-09-22T23:36:26-07:00)
.RE 0

.P
The amount of time to show activity from.
.SH "SEE ALSO"
.RS 0
.IP \(bu 4
bosco help morning
.RE 0
