.TH "BOSCO-S3DELETE" "3" "December 2020" "" ""
.SH "NAME"
\fBbosco-s3delete\fR - Delete a bundled build from S3.
.SH "SYNOPSIS"
.P
.RS 2
.nf
bosco -e <environment> s3delete <build>
.fi
.RE
.SH "DESCRIPTION"
.P
This command will delete a previously pushed build from \fBbosco s3push\fR from S3 - e.g. allowing you to be a good citizen and clean up after yourself.
.P
Note that in this command the build is passed as an additional argument, not as a command line option.
.SH "COMMAND LINE OPTIONS"
.SS "-e, --environment"
.RS 0
.IP \(bu 4
Default: local
.IP \(bu 4
Type: String
.RE 0

.P
This sets the environment path
.SH "CONFIGURATION REQUIREMENTS"
.P
For this command to work you must have configured the AWS configuration within the \fB.bosco\fR configuration files. This can either be in the \fBbosco.json\fR file (which means it is common across all environments), or in a file named \fBenvironment.json\fR which means it is applied based on the environment name applied in the \fB-e\fR option.
.P
The configuration needs to contain the following:
.P
.RS 2
.nf
"aws": {
    "key": "XXX-AWS-KEY-XXX",
    "secret": "XXX-AWS-SECRET-XXX",
    "bucket": "bucket-name",
    "region": "region-name",
    "cdn": "https://your-cloudfront.cloudfront.net"
}
.fi
.RE
.SH "SEE ALSO"
.RS 0
.IP \(bu 4
bosco help s3push
.RE 0
