.TH "BOSCO-INSTALL" "3" "December 2020" "" ""
.SH "NAME"
\fBbosco-install\fR - Run npm install across all your repositories.
.SH "SYNOPSIS"
.P
.RS 2
.nf
bosco install
.fi
.RE
.SH "DESCRIPTION"
.P
This command is used to run npm install across all of the github repositories in your configured Github team.
.P
It is called as part of the two wrapper scripts: \fBsetup\fR and \fBmorning\fR.
.SH "SEE ALSO"
.RS 0
.IP \(bu 4
bosco help setup
.IP \(bu 4
bosco help morning
.RE 0
