.TH "BOSCO-CLONE" "3" "December 2020" "" ""
.SH "NAME"
\fBbosco-clone\fR - clone all repositories in your Github team.
.SH "SYNOPSIS"
.P
.RS 2
.nf
bosco clone
.fi
.RE
.SH "DESCRIPTION"
.P
This command is used to clone all of the github repositories in your configured Github team.
.P
It is called as part of the two wrapper scripts: \fBsetup\fR and \fBmorning\fR.
.SH "SEE ALSO"
.RS 0
.IP \(bu 4
bosco help setup
.IP \(bu 4
bosco help morning
.RE 0
